### ISSUE TITLE
1.1.3 is an empty release

### ISSUE THREAD

**Issue by denis-sokolov** [jedmao/eclint#34]
PRs #32 and #33 only modify the source.
I did not notice that the project has build artifacts in the repository.
Please consider #33 and then rebuild to ensure that the JavaScript version is updated.

Consider not keeping build artifacts in the repository. Although not universally accepted, I'd say it's a generally accepted practice.

Sorry for the inconvenience.

**Comment by jedmao** [comment]
Fixed in [v1.1.5](https://github.com/jedmao/eclint/blob/master/CHANGELOG.md#115), where I also added `npm test` to the prepublish script so that an empty release won't happen again.

I totally agree with not keeping build artifacts in the repo. I definitely don't do that with new projects. Anyway, the build artifacts were removed in https://github.com/jedmao/eclint/commit/93aa94904220e050cbb1470dbd6f4c0925e56aa1.

Thanks again!
