### ISSUE TITLE
Skip binary files

### ISSUE THREAD

**Issue by bfred-it** [jedmao/eclint#45]
If I were to run

```sh
$ eclint check *
```

eclint runs on all binary files, but these should be ignored, perhaps using [`is-binary-path`](https://github.com/sindresorhus/is-binary-path/blob/master/index.js) as a blacklist or [`is-text-path`](https://github.com/sindresorhus/is-text-path/blob/master/index.js) as a whitelist

**Comment by jedmao** [comment]
The EditorConfig js core is one of many cores and should be the one responsible for handling this request. I think this issue would be best requested in the general EditorConfig issue tracker so that all cores would ignore binary files, if accepted. Until then, i don't think this is an eclint concern.

**Comment by jedmao** [comment]
Reopening in response to https://github.com/editorconfig/editorconfig-core-js/issues/42#issuecomment-273396875. Willing to accept a PR, but I'm not really maintaining this project any more these days.

**Comment by gucong3000** [comment]
@bfred-it fixed in master branch.

**Comment by bfred-it** [comment]
Excellent! Thank you 🙂

**Comment by jedmao** [comment]
I haven't released what's on master yet though. I'm waiting for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14996.

**Comment by jedmao** [comment]
The type def has landed!
